### ISSUE TITLE
코드 수정 요청 사항

### ISSUE THREAD

**Issue by snoopspy** [hwanj-95/send-arp#1]
https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660105

https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660110

https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660117

https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660120

https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660128

https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660129

**Comment by hwanj-95** [comment]
done in https://github.com/hwanj-95/send-arp/commit/ff19446df423b598456d3de851aecd6259a4d4b7?diff=split
https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660105
https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660110
https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660117
https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660120
https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660128
https://github.com/hwanj-95/send-arp/commit/8bb046daea7f75ca23aa41d646bed5fa3393eaa1#r38660129

**Comment by snoopspy** [comment]
수고하셨습니다.
